### PR TITLE
msrv: fix Jiff build on Windows for Rust 1.71

### LINKED ISSUE #566: "restricted type `DYNAMIC_TIME_ZONE_INFORMATION` in public interface" with `v0.2.26`
Hi,

I noticed in our [CI](https://github.com/uutils/parse_datetime/pull/297) that the new release (`v0.2.26`) fails on `windows-latest` with Rust `1.71.1` with the following error:
```
error[E0446]: restricted type `DYNAMIC_TIME_ZONE_INFORMATION` in public interface
  --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\jiff-0.2.26\src\tz\system\windows\ffi.rs:35:1
   |
4  | pub(super) struct DYNAMIC_TIME_ZONE_INFORMATION {
   | ----------------------------------------------- `DYNAMIC_TIME_ZONE_INFORMATION` declared as restricted
...
35 | windows_link::link!("kernel32.dll" "system" fn GetDynamicTimeZoneInformation(info: *mut DYNAMIC_TIME_ZONE_INFORMATION) -> u32);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak restricted type
```

### PR DESCRIPTION
**Pull request by BurntSushi**
Fixes #566

### CODE REVIEW

**Comment by BurntSushi** [comment]
Oh this isn't working right now because

actions
